### ISSUE TITLE
Next.js 13.2 - Built-in SEO support with new Metadata API

### ISSUE THREAD

**Issue by hyunnnn98** [Samsam-lee/NextJS#1]
## [Built-in SEO support with new Metadata API](https://nextjs.org/blog/next-13-2#built-in-seo-support-with-new-metadata-api)
The new Metadata API allows you to define metadata (e.g. meta and link tags inside your HTML head element) with an explicit metadata configuration in any layout or page that is a Server Component.

```ts
// Static metadata
export const metadata = {
  title: '...',
};

// Dynamic metadata
export async function generateMetadata({ params, searchParams }) {
  const product = await getProduct(params.id);
  return { title: product.title };
}

```

지금 레포에서는 SEO 컴포넌트를 따로 빼서 설정하고 있던데
Next.js 13.2 부터 업데이트된 메타데이터 API를 사용하면 코드상에서 명시적으로 메타데이터 구성이 가능해요!

### Current
```ts
import Seo from "../components/Seo"

export default function About() {
  return (
    <div>
      <Seo title="About" />
      <div>About Page</div>
    </div>
  );
```

### Suggested change
```ts
export const metadata = {
  title: 'About',
};

export default function About() {
  return (
    <div>
      <div>About Page</div>
    </div>
  );
}
```

### ref.
- https://twitter.com/nextjs/status/1630587612682395648?s=20

**Comment by LeeJaeBae** [comment]
ㅇㅅㅇ!
